// <auto-generated />
namespace Trolllo.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AttendToProjectEntityandSuccesonProject : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AttendToProjectEntityandSuccesonProject));
        
        string IMigrationMetadata.Id
        {
            get { return "201611161616313_AttendToProjectEntity and Succes on Project"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
